Repository Am10aN16/cppnotes, pull requests merged in 2022-10, with the labels that each got.

#1 Create mergesortedarray.cpp
  mergesortedarray.cpp
Labels: good first issue, hactoberfest-accepted

#2 Create baseballgame leetcode.cpp
  baseballgame leetcode.cpp
Labels: enhancement, hactoberfest-accepted

#3 Moving zero leetcode problem
  count item matching a rule leetcode.cpp
  move zeros leetcode.cpp
Labels: good first issue, hactoberfest-accepted

#4 Create kidshavemaxcandies leetcode.cpp
  kidshavemaxcandies leetcode.cpp
Labels: enhancement, help wanted, good first issue, hactoberfest-accepted
